#ifndef HASKELL_STEP_BY_STEP_EVALUATOR_CONTROLLERCOMMAND_H
#define HASKELL_STEP_BY_STEP_EVALUATOR_CONTROLLERCOMMAND_H

enum class ControllerCommand {STEP_FORWARD, STEP_IN, STEP_OUT, BAD_COMMAND};

#endif //HASKELL_STEP_BY_STEP_EVALUATOR_CONTROLLERCOMMAND_H
